baseurl = "https://example.com"
languageCode = "en"
title = "/dev/notes"
theme = "kiss"
copyright = "&copy; <a href=\"https://github.com/gpeddle\">Greg Peddle</a>"
#disqusShortname = "shortname"
googleAnalytics = ""
Paginate = 5 # Number of posts per page
enableRobotsTXT = true

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Greg Peddle" # Author full name
authorEmail = "gpeddle@gmail.com" # Author email

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
adsense = "" # Adsense ID (ID only, without ca-pub-)
enableSocial = true # Adds OpenGraph and Twitter cards
homeTitle = "Notes on Software Development" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks
taxonomiesCount = true # Add taxonomies count

[params.features]
disqusOnDemand = false  # Load Disqus comments on click


[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]
twitter = "gpeddle"
github = "gpeddle"
email = "gpeddle@gmail.com"
linkedin = "gpeddle"
facebook = ""
instagram = ""
codepen = ""
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin"]

#[params.matomoAnalytics]
#siteID = 1
#rootURL = "//matomo.example.com/"

#[params.fathomAnalytics]
#rootURL = "//fathom.example.com/"

#[params.hotjarAnalytics]
#hjid = 1

#[params.plausibleAnalytics]
#domain = ribice.ba

[taxonomies]
tag ="tags"

[blackfriday]